In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('http://taanila.fi/sales_data_sample.csv', encoding='cp1252')
df.head(10)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
5,10168,36,96.66,1,3479.76,10/28/2003 0:00,Shipped,4,10,2003,...,9408 Furth Circle,NaN,Burlingame,CA,94217,USA,NaN,Hirano,Juri,Medium
6,10180,29,86.13,9,2497.77,11/11/2003 0:00,Shipped,4,11,2003,...,"184, chausse de Tournai",NaN,Lille,NaN,59000,France,EMEA,Rance,Martine,Small
7,10188,48,100.00,1,5512.32,11/18/2003 0:00,Shipped,4,11,2003,...,"Drammen 121, PR 744 Sentrum",NaN,Bergen,NaN,N 5804,Norway,EMEA,Oeztan,Veysel,Medium
8,10201,22,98.57,2,2168.54,12/1/2003 0:00,Shipped,4,12,2003,...,5557 North Pendale Street,NaN,San Francisco,CA,NaN,USA,NaN,Murphy,Julie,Small
9,10211,41,100.00,14,4708.44,1/15/2004 0:00,Shipped,1,1,2004,...,"25, rue Lauriston",NaN,Paris,NaN,75016,France,EMEA,Perrier,Dominique,Medium

In [4]:
df[df['PRICEEACH']>90]

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
5,10168,36,96.66,1,3479.76,10/28/2003 0:00,Shipped,4,10,2003,...,9408 Furth Circle,NaN,Burlingame,CA,94217,USA,NaN,Hirano,Juri,Medium
7,10188,48,100.00,1,5512.32,11/18/2003 0:00,Shipped,4,11,2003,...,"Drammen 121, PR 744 Sentrum",NaN,Bergen,NaN,N 5804,Norway,EMEA,Oeztan,Veysel,Medium
8,10201,22,98.57,2,2168.54,12/1/2003 0:00,Shipped,4,12,2003,...,5557 North Pendale Street,NaN,San Francisco,CA,NaN,USA,NaN,Murphy,Julie,Small
9,10211,41,100.00,14,4708.44,1/15/2004 0:00,Shipped,1,1,2004,...,"25, rue Lauriston",NaN,Paris,NaN,75016,France,EMEA,Perrier,Dominique,Medium
10,10223,37,100.00,1,3965.66,2/20/2004 0:00,Shipped,1,2,2004,...,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,APAC,Ferguson,Peter,Medium
11,10237,23,100.00,7,2333.12,4/5/2004 0:00,Shipped,2,4,2004,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,NaN,Frick,Michael,Small
12,10251,28,100.00,2,3188.64,5/18/2004 0:00,Shipped,2,5,2004,...,7476 Moss Rd.,NaN,Newark,NJ,94019,USA,NaN,Brown,William,Medium
13,10263,34,100.00,2,3676.76,6/28/2004 0:00,Shipped,2,6,2004,...,25593 South Bay Ln.,NaN,Bridgewater,CT,97562,USA,NaN,King,Julie,Medium
14,10275,45,92.83,1,4177.35,7/23/2004 0:00,Shipped,3,7,2004,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium
15,10285,36,100.00,6,4099.68,8/27/2004 0:00,Shipped,3,8,2004,...,39323 Spinnaker Dr.,NaN,Cambridge,MA,51247,USA,NaN,Hernandez,Marta,Medium
16,10299,23,100.00,9,2597.39,9/30/2004 0:00,Shipped,3,9,2004,...,Keskuskatu 45,NaN,Helsinki,NaN,21240,Finland,EMEA,Karttunen,Matti,Small
17,10309,41,100.00,5,4394.38,10/15/2004 0:00,Shipped,4,10,2004,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
18,10318,46,94.74,1,4358.04,11/2/2004 0:00,Shipped,4,11,2004,...,7586 Pompton St.,NaN,Allentown,PA,70267,USA,NaN,Yu,Kyung,Medium
19,10329,42,100.00,1,4396.14,11/15/2004 0:00,Shipped,4,11,2004,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
20,10341,41,100.00,9,7737.93,11/24/2004 0:00,Shipped,4,11,2004,...,Geislweg 14,NaN,Salzburg,NaN,5020,Austria,EMEA,Pipps,Georg,Large
24,10403,24,100.00,7,2434.56,4/8/2005 0:00,Shipped,2,4,2005,...,Berkeley Gardens 12 Brewery,NaN,Liverpool,NaN,WX1 6LT,UK,EMEA,Devon,Elizabeth,Small
25,10417,66,100.00,2,7516.08,5/13/2005 0:00,Disputed,2,5,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Large
26,10103,26,100.00,11,5404.62,1/29/2003 0:00,Shipped,1,1,2003,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
27,10112,29,100.00,1,7209.11,3/24/2003 0:00,Shipped,1,3,2003,...,Berguvsvâ€žgen 8,NaN,Lule,NaN,S-958 22,Sweden,EMEA,Berglund,Christina,Large
28,10126,38,100.00,11,7329.06,5/28/2003 0:00,Shipped,2,5,2003,...,"C/ Araquil, 67",NaN,Madrid,NaN,28023,Spain,EMEA,Sommer,MartÂ¡n,Large
29,10140,37,100.00,11,7374.10,7/24/2003 0:00,Shipped,3,7,2003,...,9408 Furth Circle,NaN,Burlingame,CA,94217,USA,NaN,Hirano,Juri,Large
30,10150,45,100.00,8,10993.50,9/19/2003 0:00,Shipped,3,9,2003,...,"Bronz Sok., Bronz Apt. 3/6 Tesvikiye",NaN,Singapore,NaN,79903,Singapore,Japan,Natividad,Eric,Large
31,10163,21,100.00,1,4860.24,10/20/2003 0:00,Shipped,4,10,2003,...,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,NaN,Hernandez,Maria,Medium
32,10174,34,100.00,4,8014.82,11/6/2003 0:00,Shipped,4,11,2003,...,31 Duncan St. West End,NaN,South Brisbane,Queensland,4101,Australia,APAC,Calaghan,Tony,Large
33,10183,23,100.00,8,5372.57,11/13/2003 0:00,Shipped,4,11,2003,...,782 First Street,NaN,Philadelphia,PA,71270,USA,NaN,Cervantes,Francisca,Medium
34,10194,42,100.00,11,7290.36,11/25/2003 0:00,Shipped,4,11,2003,...,"2, rue du Commerce",NaN,Lyon,NaN,69004,France,EMEA,Saveley,Mary,Large
35,10206,47,100.00,6,9064.89,12/5/2003 0:00,Shipped,4,12,2003,...,1900 Oak St.,NaN,Vancouver,BC,V3F 2K1,Canada,NaN,Tannamuri,Yoshi,Large
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2702,10232,48,96.16,1,4615.68,3/20/2004 0:00,Shipped,1,3,2004,...,Garden House Crowther Way,NaN,Cowes,Isle of Wight,PO31 7PJ,UK,EMEA,Bennett,Helen,Medium
2703,10248,30,100.00,7,3245.40,5/7/2004 0:00,Cancelled,2,5,2004,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
2707,10295,34,100.00,5,3473.78,9/10/2004 0:00,Shipped,3,9,2004,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium
2708,10306,32,90.15,4,2884.80,10/14/2004 0:00,Shipped,4,10,2004,...,Fauntleroy Circus,NaN,Manchester,NaN,EC2 5NT,UK,EMEA,Ashworth,Victoria,Small
2713,10373,34,96.34,2,3275.56,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2714,10386,45,92.08,2,4143.60,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2715,10397,48,100.00,3,5192.64,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Medium
2716,10414,28,100.00,7,3029.04,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium
2717,10105,22,100.00,7,2556.18,2/11/2003 0:00,Shipped,1,2,2003,...,Vinb'ltet 34,NaN,Kobenhavn,NaN,1734,Denmark,EMEA,Petersen,Jytte,Small
2721,10153,20,100.00,3,2204.60,9/28/2003 0:00,Shipped,3,9,2003,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2722,10167,28,100.00,14,3003.00,10/23/2003 0:00,Cancelled,4,10,2003,...,?kergatan 24,NaN,Boras,NaN,S-844 67,Sweden,EMEA,Larsson,Maria,Medium
2723,10177,24,100.00,5,2526.48,11/7/2003 0:00,Shipped,4,11,2003,...,"Merchants House, 27-30 Merchant's Quay",NaN,Madrid,NaN,28023,Spain,EMEA,Fernandez,Jesus,Small
2725,10197,35,93.35,11,3267.25,11/26/2003 0:00,Shipped,4,11,2003,...,"Rambla de CataluÂ¤a, 23",NaN,Barcelona,NaN,8022,Spain,EMEA,Saavedra,Eduardo,Medium
2727,10222,31,95.34,17,2955.54,2/19/2004 0:00,Shipped,1,2,2004,...,361 Furth Circle,NaN,San Diego,CA,91217,USA,NaN,Thompson,Valarie,Small
2729,10248,35,90.37,8,3162.95,5/7/2004 0:00,Cancelled,2,5,2004,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
2731,10273,26,100.00,9,2969.46,7/21/2004 0:00,Shipped,3,7,2004,...,Rue Joseph-Bens 532,NaN,Bruxelles,NaN,B-1180,Belgium,EMEA,Dewey,Catherine,Small
2733,10294,45,100.00,1,4692.60,9/10/2004 0:00,Shipped,3,9,2004,...,7635 Spinnaker Dr.,NaN,Brickhaven,MA,58339,USA,NaN,Barajas,Miguel,Medium
2734,10306,30,100.00,5,3515.70,10/14/2004 0:00,Shipped,4,10,2004,...,Fauntleroy Circus,NaN,Manchester,NaN,EC2 5NT,UK,EMEA,Ashworth,Victoria,Medium
2735,10315,37,91.37,4,3380.69,10/29/2004 0:00,Shipped,4,10,2004,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium
2738,10350,25,100.00,16,2854.75,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2739,10373,37,100.00,8,4025.60,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2740,10386,30,95.48,3,2864.40,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2741,10397,36,100.00,2,3789.72,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Medium
2742,10414,27,90.37,8,2439.99,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Small
2764,10361,35,100.00,11,4277.35,12/17/2004 0:00,Shipped,4,12,2004,...,"Monitor Money Building, 815 Pacific Hwy",Level 6,Chatswood,NSW,2067,Australia,APAC,Huxley,Adrian,Medium
2791,10361,23,95.20,12,2189.60,12/17/2004 0:00,Shipped,4,12,2004,...,"Monitor Money Building, 815 Pacific Hwy",Level 6,Chatswood,NSW,2067,Australia,APAC,Huxley,Adrian,Small
2817,10337,42,97.16,5,4080.72,11/21/2004 0:00,Shipped,4,11,2004,...,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,NaN,Hernandez,Maria,Medium
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium

In [7]:
df[df['PRICEEACH']>90].sort_values(by="PRICEEACH", ascending=False).head(10)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
1043,10287,36,100.0,5,5852.52,8/30/2004 0:00,Shipped,3,8,2004,...,Grenzacherweg 237,NaN,Gensve,NaN,1203,Switzerland,EMEA,Holz,Michael,Medium
1309,10337,29,100.0,2,4498.19,11/21/2004 0:00,Shipped,4,11,2004,...,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,NaN,Hernandez,Maria,Medium
1320,10164,45,100.0,3,5012.55,10/21/2003 0:00,Resolved,4,10,2003,...,Kirchgasse 6,NaN,Graz,NaN,8010,Austria,EMEA,Mendel,Roland,Medium
1319,10150,49,100.0,2,6467.02,9/19/2003 0:00,Shipped,3,9,2003,...,"Bronz Sok., Bronz Apt. 3/6 Tesvikiye",NaN,Singapore,NaN,79903,Singapore,Japan,Natividad,Eric,Medium
1318,10140,40,100.0,5,4601.20,7/24/2003 0:00,Shipped,3,7,2003,...,9408 Furth Circle,NaN,Burlingame,CA,94217,USA,NaN,Hirano,Juri,Medium
1317,10126,50,100.0,5,7083.00,5/28/2003 0:00,Shipped,2,5,2003,...,"C/ Araquil, 67",NaN,Madrid,NaN,28023,Spain,EMEA,Sommer,MartÂ¡n,Large
1316,10114,41,100.0,9,4815.45,4/1/2003 0:00,Shipped,2,4,2003,...,"265, boulevard Charonne",NaN,Paris,NaN,75012,France,EMEA,Bertrand,Marie,Medium
1315,10103,36,100.0,5,4228.20,1/29/2003 0:00,Shipped,1,1,2003,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
1313,10396,45,100.0,5,4739.40,3/23/2005 0:00,Shipped,1,3,2005,...,5677 Strong St.,NaN,San Rafael,CA,97562,USA,NaN,Nelson,Valarie,Medium
1310,10350,30,100.0,3,3023.10,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium